version: "3.7"

services:

  #zookeeper:
    #image: zookeeper
    #container_name: zookeeper
    #ports:
      #- "2181:2181"
    #volumes:
      #- /data/zookeeper/data:/data
      #- /data/zookeeper/datalog:/datalog
    #restart: unless-stopped

  #kafka:
    #image: wurstmeister/kafka
    #ports:
      #- "9092:9092"
    #volumes:
      #- /data/kafka:/kafka
      #- /var/run/docker.sock:/var/run/docker.sock
    #environment:
      #- KAFKA_ADVERTISED_HOST_NAME=10.10.10.10
      #- KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      #- JMX_PORT=9999
    #depends_on:
      #- zookeeper
    #restart: unless-stopped

  cmak:
    image: cmak
    container_name: cmak
    ports:
      - "9000:9000"
    environment:
      #- ZK_HOSTS=zookeeper:2181
      - ZK_HOSTS=zk1:2181,zk2:2181,zk3:2181
      - KAFKA_MANAGER_AUTH_ENABLED=true
      - KAFKA_MANAGER_USERNAME=admin
      - KAFKA_MANAGER_PASSWORD=kafka
      - KINIT_PRINCIPAL=myuaser@MYREALM
    volumes:
      - /data/cmak:/app
    depends_on:
      - zookeeper
    restart: unless-stopped
